on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 21 16 * * *
name: Semgrep
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v3
    - run: |
        echo ${{ github.repository }}
        echo ${{ vars.ORGANIZATION_NAME }}
        echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
        echo "SEMGREP_REPO_NAME=${{ vars.ORGANIZATION_NAME }}/$REPO_NAME" >> $GITHUB_ENV
        semgrep ci
