on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 21 16 * * *
env:
  # Setting an environment variable with the value of a configuration variable
  org_name: ${{ vars.ORGANIZATION_NAME }}
name: Semgrep
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_REPO_NAME: $org_name/${{ github.repository }}
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v3
    - run: |
        echo ${{ github.repository }}
        echo $org_name
        #semgrep ci
